### ISSUE TITLE
Run main on the Tests/RunBacktest.py file not working as expected.

### ISSUE THREAD

**Issue by bollingerbandit** [Ncohen10/StockAlgorithm#1]
Hello Ncohen10!

First off thank you for working on this! I've been looking for a good backtesting service for a while.

I've been trying to run a few backtests but every time I try to run main on the Tests/RunBacktest.py file using 

`python RunBacktest.py` I get the following error 

```
sudo python Tests/RunBacktest.py 
Traceback (most recent call last):
  File "Tests/RunBacktest.py", line 1, in <module>
    from StockAlgorithm.Tests.Backtesting import Backtesting
ImportError: No module named StockAlgorithm.Tests.Backtesting
```

Can you please help me with this?

**Comment by Ncohen10** [comment]
It seems like an error with the imports. Set the working directory to the parent directory of the StockAlgorithm folder and run:
```
py -m StockAlgorithm.Tests.RunBacktest
```
or
```
python -m StockAlgorithm.Tests.RunBacktest
```
Let me know if that works or if you have any questions.

**Comment by bollingerbandit** [comment]
Hello Ncohen10!

Appreciate the quick response but unfortunately I am still having issues 

```
python -m StockAlgorithm.Tests.RunBacktest


/usr/bin/python: No module named StockAlgorithm.Tests
```

**Comment by bollingerbandit** [comment]
Could it perhaps be due to my file structure or pythonpath ? I've tinkered with those as well and no luck.

**Comment by Ncohen10** [comment]
Here's a picture of my [file structure](https://imgur.com/a/FFYyF4c). Try to make your project match it. If that still doesn't work, could you send a picture of your file structure? A few people have had this issue in the past, and it was in fact a problem with the pythonpath/directories.

**Comment by Ncohen10** [comment]
Here's a screenshot of my [file structure](https://imgur.com/a/GjAj4zf) on IntelliJ IDEA. Try to make your project match it. If that still doesn't work, could you post a picture of your file structure and pythonpath? A few people have had this issue in the past, and it was in fact a problem with the pythonpath/directories.

**Comment by bollingerbandit** [comment]
Hello! Here is what my structure looks like -- its a little deeper than just under the home directrory, along with pythonpath [(/Users/bollingerbandit/Scripts/me/StockAlgorithm)]
![Screen Shot 2020-10-19 at 11 10 14 AM](https://user-images.githubusercontent.com/68570420/96470645-83775a00-11fc-11eb-9100-498a78bc2206.png)

**Comment by Ncohen10** [comment]
So it seems like an issue with the path/working directory? I think it needs to be changed to:

`/Users/bollingerbandit/Scripts/me`

and then try running:

`python -m StockAlgorithm.Tests.RunBacktest`

Also, I am running this in Python 3.8 - using an older version of Python (<3.6) may cause some issues.

**Comment by TobySack** [comment]
Since OP is on a Mac I don't know the exact solution for them but I was facing a similar issue on Windows. I made sure paths were correct but what seemed to work for me as I was using Command Prompt was running as admin.

Posting this here just in case if anyone else has issues.

**Comment by Ncohen10** [comment]
@xenos360 Thanks for the input. Marking as closed for now.

**Comment by bollingerbandit** [comment]
Hey guys .. sorry for the late response -- finally had some time to play around with this and the issue was with my python version. Worked once I used ```python3 -m StockAlgorithm.Tests.RunBacktest```

thanks for all the input on this!
